language: node_js
node_js:
  - "4.4.1"
  - "0.11"
  - "0.10"
script: "npm run-script test-travis"
branches:
  only:
    - master
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"